name: Test search
on: push
jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: build container
        run: |
          make build

      - name: run pytest
        run: |
          make check

      - name: prints output of search results
        run: |
          make run
          make SEARCHTERM=GrEaTeSt run
